version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      ports:
        "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: library_management
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: db
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  db_data:
